var annotated_dup =
[
    [ "Capacidade", "class_capacidade.html", "class_capacidade" ],
    [ "Cartao", "class_cartao.html", "class_cartao" ],
    [ "Codigo", "class_codigo.html", "class_codigo" ],
    [ "ContainerGerente", "class_container_gerente.html", "class_container_gerente" ],
    [ "ContainerHospede", "class_container_hospede.html", "class_container_hospede" ],
    [ "ContainerHotel", "class_container_hotel.html", "class_container_hotel" ],
    [ "ContainerQuarto", "class_container_quarto.html", "class_container_quarto" ],
    [ "ContainerReserva", "class_container_reserva.html", "class_container_reserva" ],
    [ "ControladoraApresentacao", "class_controladora_apresentacao.html", null ],
    [ "ControladoraHospede", "class_controladora_hospede.html", null ],
    [ "ControladoraHotel", "class_controladora_hotel.html", null ],
    [ "ControladoraQuarto", "class_controladora_quarto.html", null ],
    [ "ControladoraReserva", "class_controladora_reserva.html", null ],
    [ "ControladoraUsuario", "class_controladora_usuario.html", null ],
    [ "Data", "class_data.html", "class_data" ],
    [ "Dinheiro", "class_dinheiro.html", "class_dinheiro" ],
    [ "Email", "class_email.html", "class_email" ],
    [ "Endereco", "class_endereco.html", "class_endereco" ],
    [ "Gerente", "class_gerente.html", "class_gerente" ],
    [ "Hospede", "class_hospede.html", "class_hospede" ],
    [ "Hotel", "class_hotel.html", "class_hotel" ],
    [ "IServicoHospede", "class_i_servico_hospede.html", null ],
    [ "IServicoHotel", "class_i_servico_hotel.html", null ],
    [ "IServicoQuarto", "class_i_servico_quarto.html", null ],
    [ "IServicoReserva", "class_i_servico_reserva.html", null ],
    [ "IServicoUsuario", "class_i_servico_usuario.html", null ],
    [ "Nome", "class_nome.html", "class_nome" ],
    [ "Numero", "class_numero.html", "class_numero" ],
    [ "Pessoa", "class_pessoa.html", "class_pessoa" ],
    [ "Quarto", "class_quarto.html", "class_quarto" ],
    [ "Ramal", "class_ramal.html", "class_ramal" ],
    [ "Reserva", "class_reserva.html", "class_reserva" ],
    [ "Senha", "class_senha.html", "class_senha" ],
    [ "Telefone", "class_telefone.html", "class_telefone" ]
];